### ISSUE TITLE
Remove the red "manual bandwidth" notice at the top os the stream tab page.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#120]
https://gyazo.com/c564eefb824ca659a5482dd950163395
Dispatched from #107

**Comment by agouaillard-cosmo** [comment]
This notice is here for a reason. This is a new behaviour with respect to bandwidth that most of the previous users will not know and be worried about. A large amount of support had to be spent explaining this before we put the notice. Please confirm explicitly that you want to remove it, knowing the consequences. @chadfurman.

**Comment by chadfurman** [comment]
Confirmed.  I understand this is not the same as RTMP functionality and WebRTC has adaptive bitrate mechanisms.  As such the bitrate is a maximum cap.  If you don't put a max, it stops at 2mb.  If you put the cap too high, it stops at the available bandwidth.  There's also a CPU problem.  

Since we have good success at 4mb, we'd like to remove the red line.

**Comment by agouaillard-cosmo** [comment]
ack.

**Comment by agouaillard-cosmo** [comment]
done.
