### ISSUE TITLE
EBS - claim that input streams are not sanitized.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#132]
reported by Brad

![Screen Shot 2019-07-26 at 10 21 18 AM](https://user-images.githubusercontent.com/27793645/61958795-070db100-af90-11e9-8d42-04ae4970d040.png)

This has been addressed and validated in #112.

I tried again on my local build, and adding extra space at the end will works.

Did the tester really test and can provide evidence it breaks, and if ti dos it breaks  *because* of the strings?

I do not close this ticket, but until it is uniquivocally confirmed that this claim is valid, not time will be spend to try to find a problem that is likely not here in the first place, given the track record of sloppy testing and false claims from this tester.

@chadfurman

**Comment by chadfurman** [comment]
@agouaillard video demonstrating the problem: https://www.youtube.com/watch?v=Hwfg0XZqQyE

**Comment by agouaillard-cosmo** [comment]
There is a crash in the video, but it s not clear whether it is triggered by the spaces at the end of the strings or not. I quickly tested last night, and spaces added to the URL does not prevent successful connection. I will test the two other strings to be sure, and document step by step the testing process. Note that having a crash when you do something, unless 100% deterministic, does not mean that something is the cause (correlation does not imply causality). Short of debugging and showing it crashes internally because of that, its circumstantial.

**Comment by agouaillard-cosmo** [comment]
setup:
-------
ebs installer: ebs-studio-x64-m73-21-19081-2.exe
computer: win10 HP spectre
chrome: Version 75.0.3770.142 (Official Build) (64-bit)
location: singapore
room url: https://stage.evercast.us/rooms/62d955ee-1c28-4183-8244-3b4cd5df03b3

step-by-step:
--------------
A. sanity check:
- open chrome, join room url, accept to share webcam, see own face on screen, click "go live"
- open installed EBS, bypass the prompts, add a scene, add a source (display), click on the "Settings" button on the right down side,
- click on left hand "Stream" button,
- the stream type is already set to Evercast
- in the EBS web app, click on the "EBS Settings"
- copy the values over to the EBS native app stream setting pannel in the "Server Name", "Server Room", "Stream Key", fields.
- click Apply, then "OK",
- Click the "Start Streaming" button
EBS should start streaming, and the corresponding stream should appear in the web app.
=> Validated

B: add space to "Server Name"
- open the EBS native app. All settings fields should already be filled with previous entered values.
- add some spaces toward the end of the server name, click in "Apply", click "OK", click "Start Streaming".
EBS should start streaming, and the corresponding stream should appear in the web app.
=> validated

C:  add spaces to "server room"
EBS should start streaming, and the corresponding stream should appear in the web app.
=> "Failed to connect" Modal window.  No crash.

D: remove spaces from "Server Room", add spaces to "Stream Key"
EBS should start streaming, and the corresponding stream should appear in the web app.
=> validated

CONCLUSION: it looks like a problem only with the "Server Room" field. Crash could  not be reproduced with the above scenario.

**Comment by chadfurman** [comment]
@agouaillard there is no longer a crash now that you've added the error message.  The current issue is that there is an error message and connection fails with the spaces in place.  The expected behavior is that the spaces should be trimmed and the connection should succeed.  The spaces should be trimmed from each of the stream settings fields: url, room ID, and stream key

An additional space at the end of any of the three stream-key fields should be trimmed and not impede connection.  There is currently no crash.  The video I shared (https://www.youtube.com/watch?v=Hwfg0XZqQyE) does not show a crash, only an error message.

**Comment by agouaillard-cosmo** [comment]
additional sanity check:
- start and stop streaming several times in a row to be sure there is nothing wrong at stopping time. 
test spaces in the URL, work in any cases.
test spaces in the room ID, only works AFTER fix.
test space in the stream Key, also only works AFTER fix.

**Comment by chadfurman** [comment]
if stop EBS, delete your obs-studio settings folder in AppData, and then restart EBS, copy in the server name (leaving the spaces), room id (leaving the spaces), and stream key (no spaces when copied), it still throws an error.  This is the case on a fresh install.
If you then restart EBS, remove the spaces from the fields, and start streaming, it connects fine.
Subsequently, restarting EBS and adding the spaces back in still connects fine so I'm guessing this is what you're seeing during your validation that convinced you it was fixed.

**Comment by agouaillard-cosmo** [comment]
can you please refer to the installer name you are using, to avoid mistakes?

**Comment by agouaillard-cosmo** [comment]
can we agree on the definition of a "fresh install". I already notified you of an ambiguity between the installation on a computer that had nothing installed before, and a computer where the install has been erased. For the Icon cache for example, it makes a huge difference. Please name the two above use case the way you want, and use the naming consistently in the bug reports.

**Comment by chadfurman** [comment]
### setup:
ebs installer: ebs-studio-x64-m73-21-19082.exe
computer: win10 ThinkPad
chrome: Version 75.0.3770.142 (Official Build) (64-bit)
location: USA East Coast
room url: https://stage.evercast.us/rooms/62d955ee-1c28-4183-8244-3b4cd5df03b3

### Step-by-step
0) Join the room in your browser and stay in the room for the duration of the remaining steps
1) uninstall EBS through add/remove programs
2) delete appdata/obs-studio folder
3) delete any residual ebs folder in program files directory
4) if present, repeat the above for any OBS application installed on the system
5) install EBS from the 19082 installer mentioned above
6) open EBS using the bin folder in the EBS folder which should now be present in the Program Files directory
7) say no to the auto config wizard
8) go to setttings -> stream
9) open the room URL in your browser, go live, and access the EBS settings dialog
10) copy the server, room id, and stream key from the browser page's EBS settings dialog into the respective fields in the EBS application's stream settings panel.  *leave the whitespace, if present.  if no whitespace is present, add whitespace to the end of the stream name and room id fields*
11) save the settings
12) start streaming
13) note that you get an error message
14) start streaming again, without restarting EBS, and note that it crashes
15) restart EBS, open the stream settings panel in the EBS application's settings dialog, and remove the whitespace from the end of the server name, room id, and stream key fields
16) save settings
17) start streaming, note that it connects.
18) restart the EBS application
19) go back into the settings panel in the EBS application, go to the stream panel, and add whitespace to the end of the room id, server name, stream key fields
20) save settings
21) start streaming, note that it *still connects* even with the spaces present

Expected behavior: when uninstalling and reinstalling EBS and removing the settings folder, I expect that entering the stream settings with trailing whitespace in the EBS application does not impede the application's ability to connect. That is, the whitespace should be trimmed.  I would expect that restarting the application, removing the whitespace, and reconnecting would still start streaming (as it does), and that restarting the application and adding the spaces back in would also still start streaming as it   There should be no cases where trailing whitespace in the stream settings fields causes the application to fail to connect

**Comment by agouaillard-cosmo** [comment]
sorry, this installer is not the latest and/or does not exists.

**Comment by chadfurman** [comment]
I typo'd the installer, I'm sorry, it's  the one you've just pasted in the channel.  I'm updating the above comment.
ebs-studio-x64-m73-v21-190812.exe

**Comment by skastr0** [comment]
The last part of this issue is that the EBS settings strings from the web app dialog may contain a newline character at the end, which looks the same as a whitespace when copied into EBS. I created a PR (#153) so that these characters are trimmed as well.

**Comment by agouaillard-cosmo** [comment]
@skastr0 does you PR address completely the problem reported by @chadfurman, specifically step 13 and 14 would NOT HAPPEN anymore?

**Comment by agouaillard-cosmo** [comment]
@chadfurman as per discussion, this is believed to be fixed with the merge of PR #153.
