### ISSUE TITLE
JNS: Sending to Janus' Streamer plugin?

### ISSUE THREAD

**Issue by sommerper** [CoSMoSoftware/OBS-studio-webrtc#162]
Hello!

I can stream to a video room using the OBS settings and pointing towards the wss:// url on my server.

I can also stream to the streaming plugin using either gst-launch or ffmpeg so I know it's working.

How can I, if it's even possible, configure OBS to send the stream to the streaming plugin (Janus streamingtest.html)?

Thanks!

**Comment by agouaillard-cosmo** [comment]
you would need to add the corresponding signalling.
that means adding an additional janus websocket client (the current one is written for the video-room plugin)
adding it to the list of ramp-services
and plumbing the UI.

**Comment by 88fingerslukee** [comment]
Is there any update to this? I really need to get this working for an implementation due to COVID-19.

**Comment by agouaillard-cosmo** [comment]
Hi,

There is no update for now. We, too, have been hit by covid-19. Some of our staff have reduce working time because of kids at home, and the demand for our business has risen. It makes it extra difficult to find time for free volunteer work.

We will come to it eventually.

If it is urgent and valuable for you, please contact cosmo to get a quote and prioritise this: contact@cosmosoftware.io
