### ISSUE TITLE
Track breaking problem #211

### ISSUE THREAD

**Issue by thoopring** [CoSMoSoftware/OBS-studio-webrtc#212]
Invalid text input marked 'Troubleshooting'. Issue 211 is not resolved.

Please change issue 211 back to "open".

This is a big problem for me and I need your help.

**Comment by agouaillard-cosmo** [comment]
thoopring. In #211 You wrote the issue was "solved", twice, including when I double-checked with you.

Do you have someone who can write in proper english, who could help you with writing the tickets?

If you cannot write the ticket in proper english, and if you do not provide enough information for reproducing the problem, you will not get any help.

**Comment by thoopring** [comment]
It's my big mistake to mark it "resolved." I'm still suffering from OBS errors.
It hasn't been solved, and the following problems arise.

[Well done]
![image](https://user-images.githubusercontent.com/8147160/80325980-48f6bb00-8872-11ea-9134-702b6b363d4a.png)


[Not good]
![image](https://user-images.githubusercontent.com/8147160/80325999-52802300-8872-11ea-85de-c1051813f6dd.png)


The above situation is repeated.

**Comment by agouaillard-cosmo** [comment]
Cannot reproduce.
