### ISSUE TITLE
EBS - potential audio drift.

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#216]
Also noticed drift or some kind of sync hit taking place for the first time where audio and video were out by 3 seconds. Simply start/stopping stream fixed the sync issue. Have not experienced this with former EBS v22

**Comment by dbackeus** [comment]
I've tried out this software for the first time today using a millicast trial account and have been having noticable audio-drift. Broadcasting from my PC the audio was off by 2-3 seconds and broadcasting from my Mac currently the lag is perhaps half a second or so.

I'm a bit confused because unless I'm mistaken the streams I did earlier today were perfectly synced.

Let me know if there is anything I can do to help with debugging info etc.

**Comment by agouaillard-cosmo** [comment]
hi dbackeus,

the evercast build and the millicst builds are different.
I'm closing this EBS ticket as cannot reproduce, and I made  a separate ticket for you: #220
