### ISSUE TITLE
MC - Stereo Audio not honored?

### ISSUE THREAD

**Issue by patrickcusack** [CoSMoSoftware/OBS-studio-webrtc#223]
I am unable to receive a spatialized stereo stream from OBS-webRTC. I am running OBS-webRTC release version from the Millicast site on a macOS 10.13.6 system. 

Both the left and right streams are passed through Millicast, but the audio stream is treated as straight mono on the client side. I have confirmed that audio is arriving as a discrete left-right pair on the Blackmagic card. See the attached picture.

If this is not an OBS issue should I raise elsewhere?

![OBS-webRTC](https://user-images.githubusercontent.com/7094881/84204341-dfb4bb00-aa5f-11ea-84ae-193cdd49da3d.png)

**Comment by agouaillard-cosmo** [comment]
Hi Patrick,

This is a known limitation of the google libwebrtc implementation: by default it down mixes opus stereo to mono because all the audio processing pipeline (Echo cancellation, noise cancellation, ....) is mono. 

For streaming purposes, those audio processing features are less important than for Video Conferencing, and there are some flags to tell libwebrtc to honour Opus stereo (or multichannel). You can see here our chrome multichannel opus demo.
https://sgmedooze.cosmosoftware.io/multiopus/index.html

We had not added this flags to the Millicast version of OBS at that time. We also add added a minimal Audio Device Management module which would always default to system audio default. 

I'm going to prepare a new version of millicast's OBS-studio-webrtc on Mac for you to test today. Millicast supports all the codecs, it's just a client-side matter. Please bear with us.

**Comment by agouaillard-cosmo** [comment]
- OBS-studio-webrtc updated and SDP validated (macOS Catalina).
- ingest node updated and SDP validated.
- Viewer web app pending update.
ETA: This week.

**Comment by patrickcusack** [comment]
Thank you.

**Comment by agouaillard-cosmo** [comment]
Done and validated.

**Comment by patrickcusack** [comment]
I ran the new build on a Mojave and Catalina system. I am specifying a 2 channel input on my Decklink card. Again the meter ballistics reflect a stereo input. I have specified 2 channels on the encode page, but the audio on the Chrome player from the Millicast server is still dual mono. I have attached the webrtc-internals from the session as well as the OBS log. I hope there is something on my side that I overlooked.

[OBS_webrtcinternals.zip](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/4815928/OBS_webrtcinternals.zip)

**Comment by agouaillard-cosmo** [comment]
Hi Patrick,

We have not pushed this in production yet. So the build you have is likely to have the old Audio Device module which was ignoring input from OBS. You can Follow the bug #226 for the new ADM integration, which will add surround sound. In the mean time, you can use the Millicast dashboard for testing, in chrome, as chrome supports Black Magic Devices natively.
