### ISSUE TITLE
Using H264 codec and viewing on Firefox video is black.

### ISSUE THREAD

**Issue by rnkvogel** [CoSMoSoftware/OBS-studio-webrtc#229]
Publishing with OBS and setting codec to h264 results in only audio in Firefox 78.0.2.
Tested on Windows 10 using the latest OBS WebRTC version and also reverted back to previous build.
Both tests using h264 codec resulted in audio only when viewing on Firefox.
Tested also latest build on MAC Catalina. Video was also black with audio only when viewed on Firefox 78.02
Setting codec to VP8 you will be able to see video.
Checked plugins H264. Tested.
https://mozilla.github.io/webrtc-landing/pc_test_no_h264.html

Using built in Millicast publisher and using h264 codec does work for Firefox.

**Comment by agouaillard-cosmo** [comment]
firefox78 on which OS?

**Comment by agouaillard-cosmo** [comment]
Robert,
The fact that the millicast web publisher does not work either points to a problem on the millicast platform itself. 
I tested with OBS m84v23.2 on Mac Catalina, and firefox 78 on Mac Catalina, and could reproduced the problem.
Looking at the console log, it seems that the problem comes from a malformed TURN Server setting, which prevent the media connection from happening on the viewer side:

XML Parsing Error: not well-formed
Location: https://turn.millicast.com/webrtc/_turn
Line Number 1, Column 1: _turn:1:1
WebRTC: Using more than two STUN/TURN servers slows down discovery 2 view.js:495
WebRTC: Using five or more STUN/TURN servers causes problems 3 view.js:495

You might want to check with jerry. and make sure the web-based publisher and viewers work before you file a ticket with OBS-studio-webrtc.

**Comment by rnkvogel** [comment]
Hello Dr Alex,


Sorry. I did point out the XML Parsing error on the console log as it was showing up prior test using Firefox.


Thanks,


Robert

________________________________
