### ISSUE TITLE
AWS OBS Failure

### ISSUE THREAD

**Issue by cwnuk-lfl** [CoSMoSoftware/OBS-studio-webrtc#240]
We're trying to use the modified WebRTC version of OBS to stream from a Windows 10 VM hosted on AWS with an NVIDIA Tesla T4 GPU.

Opening OBS works, but when we go to start the stream we get a popup window with the error "Starting the output failed. Please check the log for details."

The log file is attached. There are two sections that I imagine the issue may be related to. The first are messages related to failing to load modules at line 40 (the referenced dlls seem to be present at the correct paths). The second are messages around line 108 saying that the millicast_output ID is missing.

Any thoughts?

[2020-09-17 22-48-57.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5278234/2020-09-17.22-48-57.txt)

**Comment by agouaillard-cosmo** [comment]
Not a problem. 
- [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded

Not a problem: no blackmagic card
- Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
- No blackmagic support

Not a problem: no AMD hardware acceleration available:
- [AMF] AMF Test failed due to one or more errors.
- Failed to initialize module 'enc-amf.dll'

not a problem
- Module '../../obs-plugins/64bit/libEGL.dll' not loaded

problem:
- LoadLibrary failed for '../../obs-plugins/64bit/obs-outputs.dll': The specified module could not be found.
- Module '../../obs-plugins/64bit/obs-outputs.dll' not loaded
- LoadLibrary failed for '../../obs-plugins/64bit/websocketclient.dll': The specified module could not be found.
- Module '../../obs-plugins/64bit/websocketclient.dll' not loaded

Todo:
- sanity check: the abs-studio-webrtc originally available from millicast dashboard dis missing the msvc runtime, and would trigger exactly this error message. If that s the version you are using move to m84v23.2 RC 1 or RC 2, both available under the release section of this repository. 
- sanity check: verify that the file '../../obs-plugins/64bit/websocketclient.dll' exists.
- if it does, then run depdency walker, or use dll listing in msvc, to check which dll is missing on your system and eventually prevents the obs-output.dll to load.

**Comment by cwnuk-lfl** [comment]
Thank you very much for your assistance!

I've uninstalled and reinstalled with m84v23.2 RC 1 and the behavior is the same
I've confirmed that '../../obs-plugins/64bit/websocketclient.dll' exists

Running dependency walker on obs-output.dll lists many many missing dlls, primarily prefixed with "API-MS-WIN" and "EXT-MS-WIN".

**Comment by agouaillard-cosmo** [comment]
Thanks for pointing to Dependencies. I was old school.
We tried separately on several machines and had no problems. AT this stage I would like to try on the same instance type you are using. Could you please share with us the instance type, and its setting?

No need to set up an instance for us at this point, better to try from a vanilla AWS instance.

**Comment by cwnuk-lfl** [comment]
We're running an AWS G4 EC2 instance (g4dn.4xlarge) which run Tesla T4 graphic cards.

There are 3 options for video card drivers, Tesla, GRID, or Gaming. We started with the GRID drivers "optimal performance for professional visualization applications that render content such as 3D models or high-resolution videos".

After some initial issues we switched to the Gaming drivers "optimizations for gaming and are updated frequently".

**Comment by agouaillard-cosmo** [comment]
Could not reproduce.

**Comment by SCG82** [comment]
I'm not sure this is related but perhaps someone will find this useful. I personally use https://aws.amazon.com/marketplace/pp/NVIDIA-NVIDIA-Gaming-PC-Windows-Server-2019/B07STLTHM8 on a g4dn.xlarge instance with no issues when broadcasting with my fork of OBS-studio-webrtc. However, OBS will freeze up if hardware decoding is enabled for the media source I'm using. In the logs posted above, hardware decoding is enabled.

**Comment by cwnuk-lfl** [comment]
@SCG82 Interesting - we've just tried that AMI you linked with a blank OBS scene (only a color source) and it behaves the exact same way as our other instance.  All of our tests have been on Windows Server 2019 AMIs, is that the same for the tests you ran @agouaillard-cosmo?

**Comment by agouaillard** [comment]
we used the g4dn.4xlarge as you mentioned, and did not run into issues.
Right now we are putting any bug on hold waiting for the next version of our fork, which will be in par with latest BS (26), which should become available within a couple of weeks.

**Comment by cwnuk-lfl** [comment]
After starting over from scratch the issue was resolved, so the issue seems to have been with our configuration, although we're not sure where.  The initial instance had previous versions of OBS installed and removed, so it's possible something lingered after one of the uninstalls.

**Comment by agouaillard-cosmo** [comment]
Thank you for taking the time to report your results.
I m happy to hear you solved the issue.

We have also bumped into problem of configurations and data staying over, or even being shared between jobs proper and our version. Right now we are addressing it through manual protocol (we remove manually the folder), but I agree we should do something better (automated, part of the installer), about it as it will bite us again in the future.

Thanks again.
