### ISSUE TITLE
mac OBS RC 3 error Video Driver Error

### ISSUE THREAD

**Issue by matthewclickbid** [CoSMoSoftware/OBS-studio-webrtc#256]
Downloaded lastest dmg file and installed. Removed older version. Received error when attempting to start stream. 
"Starting the output failed... If you are using the NVENC or AMD encoders, make sure your video drivers are up to date."

Including log file and screenshot. Previously saw this on PC version.

[2020-11-25 11-03-15.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/5597849/2020-11-25.11-03-15.txt)
![Screen Shot 2020-11-25 at 11 04 46 AM](https://user-images.githubusercontent.com/11916448/100252952-83126300-2f0e-11eb-9660-ccd768a2c7e6.png)

**Comment by agouaillard-cosmo** [comment]
Hi matt.

This message is misleading. The real problem appears in the log (thanks for sharing them):

`os_dlopen(/Applications/OBS 2.app/Contents/Plugins/obs-outputs.so->/Applications/OBS 2.app/Contents/Plugins/obs-outputs.so): dlopen(/Applications/OBS 2.app/Contents/Plugins/obs-outputs.so, 257): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib`

Basically, we made a mistake when packaging the app, and the plugin in charge of webrtc connection still points to a local file instead of the one embedded in the app.

As a quick workaround, if you know your way around the terminal, you could install the missing OpenSSL package on your system. Otherwise, I'm going to repackage the app. Would you mind to confirm the "latest dmg" you mention, either by giving me the version number (2.xx), or the build name (e.g. m84v23.2 RC 3) or even better a link. There are a lot of installers being pushed, and the latest at the moment you write might not be the latest when i eventually dress your problem.

**Comment by matthewclickbid** [comment]
Sure. Thank you.
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/download/2.11/obs-webrtc-macOS-10.15-23.2.84.1.dmg

**Comment by agouaillard** [comment]
matthew, I'm sorry I dropped the ball on you. I will make a package today.

**Comment by agouaillard-cosmo** [comment]
HI Matthew,
I upgraded the RC3 Mac package. It should not show the error anymore.
please go ahead, and note that the building number was bumped from 1 to 2:
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/download/2.11/obs-webrtc-macOS-10.15-23.2.84.2.dmg
