### ISSUE TITLE
crash logs unavailable to access.

### ISSUE THREAD

**Issue by rnkvogel** [CoSMoSoftware/OBS-studio-webrtc#280]
Mac OS X (NSMACHOperatingSystem)
OS Version: Version 10.15.6 (Build 19G2021)
OBS 23.2 (mac)

On MAC Catalina OBS WebRTC Selecting Help>Crash Reports>Show Crash Reports> does not open crashes directory.
On MAC Catalina OBS WebRTC Selecting Help>Crash Reports>Upload Crash Reports> does nothing.

**Comment by agouaillard-cosmo** [comment]
Upload crash report upload them to OBS proper.

Can you check if the problem persists with m86v26:
https://github.com/CoSMoSoftware/OBS-studio-webrtc/releases/tag/2.16

**Comment by rnkvogel** [comment]
Dow load link obs-webrtc-2.16-m86v26.0.1.dmg . On download version and install show as 2.15-8gfc8655556. Tested streaming for an hour no issues.
The following still exist.
Mac OS X (NSMACHOperatingSystem)
OS Version: Version 10.15.6 (Build 19G2021)

On MAC Catalina OBS WebRTC Selecting Help>Crash Reports>Show Crash Reports> does not open crashes directory.
On MAC Catalina OBS WebRTC Selecting Help>Crash Reports>Upload Crash Reports> does nothing.

**Comment by agouaillard-cosmo** [comment]
- [ ] The "Upload Crash reports" uploads to OBS' servers, so we should disable this option for now. (all OSes)
- [ ] Fix show crash reports (Mac Catalina)

**Comment by ludocosmo** [comment]
The menu Help>Crash Reports>Show Crash Reports opens a finder window with the "~/Library/Application Support/obs-studio/crashes" directory selected ONLY if that directory exists.
Directory "~/Library/Application Support/obs-studio/crashes" is created when a first crash of OBS occurs.
If there have never been any crash of OBS, then directory "~/Library/Application Support/obs-studio/crashes" does not exist.

If there is no directory "~/Library/Application Support/obs-studio/crashes" then the menu Selecting Help>Crash Reports>Upload Crash Reports does nothing because there are no crash report to be uploaded.

This is the same behaviour as original OBS-Studio 26.1.2.
---------------------
If you create directory "~/Library/Application Support/obs-studio/crashes" then the menu Help>Crash Reports>Show Crash Reports will open a finder window.

The menu Selecting Help>Crash Reports>Upload Crash Reports does its job silently, but it writes a line in the log file.

**Comment by agouaillard-cosmo** [comment]
not a bug.
