### ISSUE TITLE
Ubuntu 20.10 - 26.1.2-m88 - Attempting to start Millicast stream results in "Failed to Start Streaming" message

### ISSUE THREAD

**Issue by Kasma-Corp** [CoSMoSoftware/OBS-studio-webrtc#303]
After all settings are set up, trying to start a stream results in the a message stating "Starting the output failed. Please check the log for details." All drivers are up to date. Identical settings in Windows 10 worked perfectly with no issues.

Full log file is linked but critical part is quoted below:

20:54:37.755: [obs-websocket] Update << '{
20:54:37.755:     "preview-only": false,
20:54:37.755:     "update-type": "StreamStarting"
20:54:37.755: }'
20:54:37.755: Output 'adv_stream': Tried to set a delay value on a non-encoded output
20:54:37.755: Stream output type 'millicast_output' failed to start!
[2021-02-16 20-19-20.txt]

https://obsproject.com/logs/G-aDmoyeLwBw5Qpx

**Comment by agouaillard-cosmo** [comment]
Hi kasma-Corp.

The root caused happened way before that, the software then struggled through several lines of the log and failed (miserably) at the line you pointed.

99% of the time the "millicast_output" failed to start error message is cause by a faulty plugin.
Faulty plugins are difficult to identify because the plugin design is made such that not being able to load a plugin is NOT a critical error by default.

This is the root cause of your problem:
20:19:20.371: os_dlopen(/usr//lib/obs-plugins/obs-outputs.so->/usr//lib/obs-plugins/obs-outputs.so): websocketclient.so: cannot open shared object file: No such file or directory
20:19:20.371: Module '/usr//lib/obs-plugins/obs-outputs.so' not loaded

the websocketclient shared lib cannot be loaded by ons-output, which in turns prevents ons-output from being loaded by OBS. That results in webrtc and websocket not being available to the main code.

Ludo who is in charge os the linux build will take a look and get back to you.
@ludocosmo it would be much better UX to fail gracefully (with an understandable error message) when the obs-output plugin fails to be loaded.

**Comment by ludocosmo** [comment]
Linux: added a check on environment variable LD_LIBRARY_PATH
OBS won't start if environment variable LD_LIBRARY_PATH is not set or if does not mention directory /usr/lib/obs-plugins

**Comment by ludocosmo** [comment]
To be able to stream, set the environment variable LD_LIBRARY_PATH as follows:
`export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/obs-plugins`
Then launch OBS

**Comment by agouaillard-cosmo** [comment]
done.
