### ISSUE TITLE
Connection to red5

### ISSUE THREAD

**Issue by steve-heslouin** [CoSMoSoftware/OBS-studio-webrtc#42]
Hi and thanks a lot for your well appreciated fork :) 👍 
I would have liked to know if by any chance connectivity to red5 server is on your plans ?

Thanks a lot

**Comment by agouaillard-cosmo** [comment]
Hi steve, and thank you.

I will give you more or less the same answer that we gave about camsoda in #39:

- while we had episodic contact with the red5 team on twitter, we do not have ongoing collaboration.
- "Only" the signalling support would need to be implemented.
- This is not something that we have in our (very limited = H264 for webrtc to support iOS safari) roadmap for OBS today.
- it's unlikely to happen this year as we are otherwise overcommitted far until 2019Q1, unless someone from the community makes a fork and try by themselves.

**Comment by steve-heslouin** [comment]
@agouaillard-cosmo Thanks a lot for your answer, i understand :)

**Comment by agouaillard-cosmo** [comment]
Update Q3-2019:
- we have more contacts with red5, but still no collaboration or shared dev items.
- we're not opposed to speak about it with the red5 team, but have no plan to add this right now.
- we are slightly reluctant to add red5 support by ourselves as:
  -- it usually requires help from the original team to understand the signalling and debug the first interoperability issues,
  -- it requires to have a full featured servers / infra / platform to work against, and we do not have such red5 deployment to date.
  -- it does not have a great market share (unlike wowza, whose implementation was contributed by a third-party by the way).
  -- if we had support for it, we need to tests it, and maintain it for every webrtc and OBS release, so there need to be something in it for us to make it worth it. For example, the support for SpankChain had to be deprecated when we updated to webrtc m73.
