### ISSUE TITLE
Mac OBS webrtc generated H264 stream does not seems to be understood by Firefox

### ISSUE THREAD

**Issue by agouaillard-cosmo** [CoSMoSoftware/OBS-studio-webrtc#45]
reported by @jerrychabolla

**What did you use:**
MacOS
OBS release 2.4.9
stream out using OBS, H264,
view through millicast web app in firefox on mac.

**What did you expect:**
Be able to view the video stream in any browser.

**What did you do, what happened:**
Firefox browser (on mac?) no longer displays the video, but one can still hear the audio. This issue does not exist in any other browser or using the OBS-STudio-webrtc Windows version.

**Comment by agouaillard-cosmo** [comment]
@jerrychabolla can you confirm richard report: it works with a certain spelling of H264 ?

**Comment by agouaillard** [comment]
@jerrychabolla: I figured out why my OBS was crashing for me.  We have updated our signaling system to handle account verification for the streams, which means we have an update for the payload we send to the service.

We are now requiring a "_streamId_" property in the payload.  

Because of this change, the OBS version will need an update to the way it verifies the client.

I will update the public demo files to reflect the changes as well.  Going forward users will need to sign up for an account and allocate a stream token through our Millicast API.

**Comment by jerrychabolla** [comment]
@agouaillard -disregard last one (my fault), streamId was for the viewer, not the publisher so please disregard.  The update for the publisher is an authentication update.

We are still using "name" for the stream property as before, but we do require an authentication token with our websocket via the URL path.  EX:

let ws = new WebSocket(url + '?token=' + securetoken);

payload properties are still "name", "sdp", and "codec", where name is equal to the stream name the user creates.

**Comment by Ben-cos** [comment]
@jerrychabolla We have updated OBS accordingly to your authentication logic.
 
I can't reproduce the issue, tested with Firefox on Mac and Windows. Please be free to re-open the ticket if that is not the case.
