### ISSUE TITLE
STUN/TURN support

### ISSUE THREAD

**Issue by chadfurman** [CoSMoSoftware/OBS-studio-webrtc#48]
Any plans to add this at some point?  If not, what library would you suggest and where in general (file / function?) would that library need to be integrated?

**Comment by chadfurman** [comment]
Double-interesting!  Looks like STUN is already supported...

https://github.com/CoSMoSoftware/OBS-studio-webrtc/blob/42385f0760ee377a0d59caff9c0c15005d818bf9/plugins/obs-outputs/WebRTCStream.cpp#L167

I'm guessing TURN wouldn't be too hard to add, then... I'll look into it more...

**Comment by agouaillard-cosmo** [comment]
Depending on the WebRTC stack you use, you might or might not have STUN or TURN support. If you use the official webrtc.org you have full support for STUN and TURN protocols.

Please make sure to keep in mind the license of the code, i.e. the right and the duty that are yours once you even simply read it.

I mention this as adding turn can be tricky in this case:
- you could hardcode the turn credential, but since it's open source, and GPL so your turn server would be open to the world. It s not a problem for STUN since STUN server do not relay streams, i.e. do not consume bandwidth.
- you could use a TURN API, but here again, the credentials to the TURN API would be hardcoded, open-sourced leaving your account to the TURN API provider open.
- Your last option is to make a new field for the user to enter the credentials. In conjunction with a TURN API like provided by Xirsys, this is the less-user-interaction solution IMHO.

**Comment by chadfurman** [comment]
We use Janus in the background and yes we wouldn't be hard coding creds as the code is open source ( https://github.com/clevertech/OBS-studio-webrtc/blob/feature/evercast-integration-merge/plugins/obs-outputs/WebRTCStream.cpp#L145

**Comment by chadfurman** [comment]
Unrelated note:. We are in the process of merging the latest EBS upstream into our code.  It's diverged a bit from yours but we are looking into ways to regain windows compatibility and bundle libwebrtc into the whole deal to make maintenance and distribution easier in the future.

Ideally all of this would go upstream eventually, solving lots of issues and gaining more support from the OBS devs themselves.  We've been in contact with them through their discord channel :)

**Comment by agouaillard-cosmo** [comment]
your using janus in the background as nothing to do with the issue hand. please keep the discussion on the topic.

you are not using libwebrtc, you are using an old cosmo package with patches, extra cmake scripts, and much more otherwise you would need much more modifications. Open source code give you the opportunity to make modification, but it does not automagically grant you the capacity to do them.

Feel free to look into the chromium source code, and/or the webrtc source code. Would you have questions, the discuss-webrtc mailing list is at your disposal. Beware, they aren't a lot of people with knowledge of the C++ side of things. Make sure not to antagonise them, or you will be on your own.
