### ISSUE TITLE
Start Streaming button locks up after Stop Streaming

### ISSUE THREAD

**Issue by david-bui** [CoSMoSoftware/OBS-studio-webrtc#55]
Step to reproduce : 
- Compile OBS for Windows
- Run OBS
- Start Streaming on wss://live.millicast.com:443/ws/v1/pub?token=d29778e3f9899f543d587556d50b65a004c6f8026e648d5e7a65bcd6f08f1ba7 , stream name : david
- Click on Stop streaming
- Click Start streaming

What is expected : 
- Green square indicating stream started

What happened : 
- The button "Start Streaming" is locked and stream does not start.

The only way to stream again is to exit and start OBS again.

logs : 
[obs.logs.david.txt](https://github.com/CoSMoSoftware/OBS-studio-webrtc/files/2500041/obs.logs.david.txt)

**Comment by Ben-cos** [comment]
This happens because we are not closing properly the WebSocket connection.

There is not close handshake send to the server (FIN + ACK). So on the server point of view, we are still connected. So when we try to publish again, we are receiving an error message indicating that this account is already publishing.

Some refactoring on the WebSocket part will be needed.  Waiting for a proper fix, we now disconnect correctly we are receiving an error message.

**Comment by Ben-cos** [comment]
Acknowledge @agouaillard-cosmo 
This issue has been fixed with commit 5e2ae36

**Comment by agouaillard-cosmo** [comment]
how to independently validate that the bug has been fixed?

**Comment by Ben-cos** [comment]
We now unpublish the stream before closing the connection to the Millicast's servers.

- Compile and run OBS
- Fillup Millicast credentials 
- Start publishing
- Open a viewer client to get the stream
- Stop publishing  
- Start publishing again, there is no error anymore.
- Refresh the viewer client and checked if we correctly get the stream.
- Stop again, and start .. repeat...
