### ISSUE TITLE
Add getStats

### ISSUE THREAD

**Issue by ValentinRamirezCosmo** [CoSMoSoftware/OBS-studio-webrtc#80]
Add GetStats to OBS

**Comment by agouaillard-cosmo** [comment]
valentin, status update please.

**Comment by ValentinRamirezCosmo** [comment]
Did not start this yet. I'm going to work on that.

**Comment by SCG82** [comment]
#134

**Comment by SCG82** [comment]
Bitrate display (from PR #134/147) appears to be functioning well.

**Comment by agouaillard-cosmo** [comment]
@SCG82. Yes it does however, this ticket is about something more ambitious: adding support for all teh stats that a web app would have access to in JS (getStats() APIs), in such a way that a testing tool, like KITE can automatically instrument the client and extract realtime stats, that are consistent with the one extracted from a web app.

**Comment by QuentinColliezCSM** [comment]
I'm trying to add the available stats in webrtc.

The problem is I have to call the _NewGetStats_ function but this function is a locked one and it's already called somewhere else. If I call it in my function the app crash. So I have tried to move the _NewGetStats_ function in order to call it only one time and use the data after for both functions. But the _NewGetStats_ function is a C++ one. And the code start in a C++ file go to a C file and after go back to a C++ file if I want to call the _NewGetStats_ function only one time. I'm trying to find a way to skip the C file.

A little scheme of the problem.

The C++ file
where the function.............................The C++ file
call the functions................................where the two
needs the...........................................function needs
  _NewGetStats_..................................... _NewGetStats_
function...................The C file.............function
+-----------------+....+-----------------+....+-----------------+
| .....................|.....|......................|.....|.....................|
| ........C++......|-->|...........C.........|-->| ........C++......|
| .....................|.....|......................|.....|.....................|
+-----------------+....+-----------------+....+-----------------+

**Comment by agouaillard-cosmo** [comment]
@ludocosmo , you deal with that?

**Comment by namvuCosmo** [comment]
Confirmed
